version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: npm run type-check
      - run: npm run test
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: npm run build
