version: 2.1
executors:
  default:
    docker:
      - image: circleci/node
commands:
  restore_node_modules:
    steps:
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
  cache_node_modules:
    steps:
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
          paths:
            - node_modules
jobs:
  test:
    executor: default
    steps:
      - checkout
      - restore_node_modules
      - run: npm install
      - cache_node_modules
      - run: npx run type-check
      - run: npm run test
  build:
    executor: default
    steps:
      - checkout
      - restore_node_modules
      - run: npm install
      - cache_node_modules
      - run: npm run build
workflows:
  version: 2
  master:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - build:
          filters:
            branches:
              only: master